version: '2'
services:
    nexus:
        restart: always
        image: nexus:jre8-alpine
        container_name: nexus
        ports:
            - 8081:8081
        volumes:
            - data:/var/lib/nexus

volumes:
    data: {}
